### ISSUE TITLE
Spinner icon spins container

### ISSUE THREAD

**Issue by bisonator1** [babelattke/tastyigniter-green#3]
Loading icon spins the container (button bar) as well as the spinner itself. This seems to be on the large buttons. Noticed on login, registration and review submission.

![image](https://user-images.githubusercontent.com/81396301/112567152-40876700-8dd8-11eb-8b32-b967e19c4c4d.png)

**Comment by babelattke** [comment]
Fixed on version 0.1.9. Please update
