### ISSUE TITLE
Cart notification doesn't add up or subtract item

### ISSUE THREAD

**Issue by fabs993** [babelattke/tastyigniter-green#5]
Hey Babel,
Hey guys,

so I found a tiny bug that occured with the cart update 2.6.0. This bug only occurs on mobile.

Bug description:
If you add items from the menu to the cart, the notifaction doesn't add up in the same instance. If you reload, the notifaction gets updated accordingly to the number of items inside the cart. The same issues vice versa. If you delete something from the cart it doesn't subtract it in the same instance, just with a page reload.

**Comment by babelattke** [comment]
Fixed on version 0.1.9. Please update
